---
- name: Install core
  hosts: all
  connection: local

  pre_tasks:
    - name: cache
      become: true
      pacman:
        update_cache: true
        upgrade: true
      when: ansible_os_family == "Archlinux"

  tasks:
    - name: Install packages
      package:
        name: "{{ item }}"
        state: latest
      loop: "{{ core_packages }}"
      become: true

- name: Install workstation
  hosts: workstation
  connection: local

  roles:
    - zsh
    - tmux
    - yay
    - font
    - dotfiles

  tasks:
    - name: Install packages
      package:
        name: "{{ item }}"
        state: latest
      loop: "{{ workstation_packages }}"
      become: true

    - name: XDG user dirs
      shell: xdg-user-dirs-update
